# Generated by Django 4.0.5 on 2024-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_skill_customer_address_customer_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='experience_level',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
