# Generated by Django 5.1.3 on 2024-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_customer_skills_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="facebook",
            field=models.URLField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="instagram",
            field=models.URLField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="linkedin",
            field=models.URLField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="twitter",
            field=models.URLField(blank=True, default="N/A", null=True),
        ),
    ]
