# Generated by Django 5.1.3 on 2024-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_customer_facebook_alter_customer_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="license_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/users/licenses/"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
