# Generated by Django 5.1.3 on 2024-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_customer_license_image_customer_license_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit",
            field=models.IntegerField(default=20),
        ),
    ]
