# Generated by Django 5.1.3 on 2024-11-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_customer_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("participant_emails", models.JSONField()),
                ("meeting_link", models.URLField()),
                ("meeting_code", models.CharField(max_length=10, unique=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="invited_meetings", to="store.customer"
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_meetings",
                        to="store.customer",
                    ),
                ),
            ],
        ),
    ]
