# Generated by Django 5.1.3 on 2024-11-19 05:16

import store.models.meetings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uid", models.CharField(max_length=1000)),
                ("room_name", models.CharField(max_length=200)),
                ("insession", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="date",
            field=models.DateField(default=store.models.meetings.current_canada_date),
        ),
        migrations.AddField(
            model_name="meeting",
            name="time",
            field=models.TimeField(default=store.models.meetings.current_canada_time),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="participant_emails",
            field=models.JSONField(default=list),
        ),
    ]
