# Generated by Django 5.1.3 on 2024-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_customerrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profileComplete",
            field=models.IntegerField(default=40),
        ),
    ]
